# Generated by Django 4.1.4 on 2022-12-22 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='likes',
            field=models.ManyToManyField(related_name='bloglike_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
