# Generated by Django 4.1.4 on 2022-12-26 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0002_postblog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='dislikes',
            field=models.ManyToManyField(related_name='blogdislike_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
