# Generated by Django 4.1.4 on 2023-01-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_postblog_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
