# Generated by Django 4.1.4 on 2023-01-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_postblog_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
