# Generated by Django 4.1.4 on 2023-01-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_remove_ordermodel_product_stockmodel_cartmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
