# Generated by Django 4.1.4 on 2023-01-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0007_addcartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcartmodel',
            name='stock',
        ),
    ]
