# Generated by Django 4.1.4 on 2022-12-26 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0003_postblog_dislikes'),
        ('blogcomment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogratingmodel_post', to='blogapp.postblog')),
                ('rater', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blogratingmodel_rater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
