# Generated by Django 4.1.4 on 2022-12-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcomment', '0002_blogratingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogratingmodel',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True),
        ),
    ]
