# Generated by Django 4.1.4 on 2023-01-09 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogcomment', '0003_alter_blogratingmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentmodel',
            name='dislikes',
            field=models.ManyToManyField(related_name='commentdislike_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='likes',
            field=models.ManyToManyField(related_name='commentlike_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
